TWEAK_NAME = Ink
Ink_FILES = MediaPlayer/InkMediaPlayer.m Notifications/InkNotifications.m
Ink_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
Ink_FRAMEWORKS = UIKit
Ink_PRIVATE_FRAMEWORKS = MediaRemote

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
